input_namespace:
  metadata: processdenguedata
  fasta: splitgenomeandqc
output_namespace: out
params:
  "Number of sequences (local)": 10
  "Number of sequences (background)": 100
  "Time Interval": "Year"
  "Sampling Method": "Even"
  "Serotypes":
    - "Serotype": "denv1"
      "Filename": "Dengue_1"
    - "Serotype": "denv2"
      "Filename": "Dengue_2"
    - "Serotype": "denv3"
      "Filename": "Dengue_3"
    - "Serotype": "denv4"
      "Filename": "Dengue_4"
