input_namespace:
  file: file
  end: end
output_namespace: out
params:
  filename: data.txt
  cols: ""
  joint: ""
  interval: 0.1  # (mins) = 6 seconds
  "Update on modify": true
  "End trigger file": trigger
  "Ready trigger file": ready
