name: Auto-Merge PRs

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - labeled

jobs:
  auto-merge:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Check if PR has auto-merge label and is from correct author
      id: check-pr
      run: |
        PR_AUTHOR=$(jq --raw-output .pull_request.user.login "$GITHUB_EVENT_PATH")
        PR_LABELS=$(jq --raw-output '.pull_request.labels | map(.name) | join(",")' "$GITHUB_EVENT_PATH")

        echo "PR Author: $PR_AUTHOR"
        echo "PR Labels: $PR_LABELS"

        if [[ "$PR_AUTHOR" == "github-actions[bot]" && "$PR_LABELS" == *"auto-merge"* ]]; then
          echo "continue=true" >> $GITHUB_ENV
        else
          echo "continue=false" >> $GITHUB_ENV
        fi

    - name: Check mergeability and auto-merge PR
      if: env.continue == 'true'
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      run: |
        PR_NUMBER=$(jq --raw-output .pull_request.number "$GITHUB_EVENT_PATH")

        MAX_RETRIES=5
        RETRY_COUNT=0
        SLEEP_TIME=10

        while [ $RETRY_COUNT -lt $MAX_RETRIES ]; do
          RESPONSE=$(curl -s -H "Authorization: token $GITHUB_TOKEN" \
                         -H "Accept: application/vnd.github.v3+json" \
                         "https://api.github.com/repos/${{ github.repository }}/pulls/${PR_NUMBER}")
          MERGEABLE=$(echo "$RESPONSE" | jq --raw-output .mergeable)
          MERGEABLE_STATE=$(echo "$RESPONSE" | jq --raw-output .mergeable_state)

          echo "Mergeable: $MERGEABLE"
          echo "Mergeable State: $MERGEABLE_STATE"

          if [[ "$MERGEABLE_STATE" == "unstable" ]]; then
            echo "Mergeable state is unstable. Retrying in $SLEEP_TIME seconds..."
            ((RETRY_COUNT++))
            sleep $SLEEP_TIME
          else
            break
          fi
        done

        if [[ "$MERGEABLE" == "true" ]]; then
          echo "PR is mergeable. Proceeding to merge."
          curl -s -X PUT -H "Authorization: token $GITHUB_TOKEN" \
               -H "Accept: application/vnd.github.v3+json" \
               "https://api.github.com/repos/${{ github.repository }}/pulls/${PR_NUMBER}/merge" \
               -d '{"merge_method":"merge"}'
        else
          echo "PR is not mergeable. Merge state: $MERGEABLE_STATE"
          exit 1
