name: Check for outlawed channels

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.11
      - name: Check for outlawed channels
        shell: bash -l {0}
        run: |
          python -m pip install --upgrade pip
          python -m pip install yaml
          python channel_check.py .
