name: Update manifest
on:
  push:
    branches:
      - main
jobs:
  update_manifest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Update manifest
        run: python manifest.py
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: update manifest
          title: Update manifest
          body: Update repository manifest file
          branch: update-manifest
          labels: auto-merge
