name: Test on pull request

on:
  pull_request:
    branches:
      - main
  event_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Run tests
        run: |
          MAIN_BRANCH_HASH=$(git rev-parse origin/main)
          FORK_COMMIT_HASH=${{ github.sha }}
          python tests/pull_tests.py $MAIN_BRANCH_HASH $FORK_COMMIT_HASH
